### PR TITLE
fix: correct Dockerfile for proper building

### PR DESCRIPTION
**Pull request by miltoncamachocamacho**
This changes update the library names and the binds from the build stage to the running stage of the build.

### CODE REVIEW

**Comment by roopchansinghv** [comment]
Could you pls update the PR to include the specific version of the Ubuntu container you are using in the Dockerfile?

We left it at "ubuntu:latest" as we thought package names and dependencies would have stayed more consistent over time.  But since these seem to change with version of Ubuntu used, then it would be good to include that information as well.

Thank you!

**Comment by miltoncamacho** [comment]
I have fixed the version of the docker image to ubuntu:24.04

I made some changes to make the conversion errors more informative using try-catch. Perhaps it would be better to try to add debug flag, but I found it useful to debug the conversion of some images.

Best!

**Comment by roopchansinghv** [comment]
Hi @miltoncamacho and/or @miltoncamachocamacho - there are more changes in here than are needed to update the Dockerfile to reflect the new package names schemes in the latest version of Ubuntu.

It's not a great idea to have changes for different things in the same commit, much less the same pull request.

I will try to get the Docker file changes rolled in, but the improving the handling of conversion errors should be their own commits and pull request.

**Comment by miltoncamacho** [comment]
Hi @roopchansinghv, I corrected as you suggested.

Thanks

**Comment by roopchansinghv** [comment]
Hey @miltoncamachocamacho - I've not forgotten, nor am ignoring this.

However, I've been trying to run local Docker builds with the updated configurations, and I keep getting errors about not being able to verify Ubuntu repositories from within the containers, and SSL key verification.  Did you run into these, and if so - how did you work around these?

**Comment by roopchansinghv** [comment]
Was finally able to run the Docker pipeline to build the container and convert ScanArchives to ISMRMRD files.

I reverted the container designation to ubuntu:latest to track the latest LTS release of that container.  Otherwise, things look good, and changes have been merged.

**Pull request merged**
